# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/neato',
                'doc_host': 'https://felipexavier11.github.io',
                'git_url': 'https://github.com/felipexavier11/neato',
                'lib_path': 'neato'},
  'syms': {'neato.core': {'neato.core.foo': ('core.html#foo', 'neato/core.py')}}}
